"""tests/test_structured_log.py — 结构化日志 + trace_id 测试。

策略:
- 用专用 logger + StringIO handler(挂 JSONFormatter), 不污染 root logger,
  也不依赖 stdout 捕获, 便于并行/重入。
- contextvars 在每个测试函数退出时由 trace_context reset; 额外显式
  reset 兜底防跨用例污染。
- 全部 Mock 思路: 不真实装 root, 不真实跑 serve.py。
"""
from __future__ import annotations

import io
import json
import logging
from contextlib import contextmanager

import pytest

from src.core.runtime.structured_log import (
    JSONFormatter,
    SPAN,
    TRACE,
    get_trace_id,
    install_json_logging,
    trace_context,
)


@contextmanager
def _capture_logger(name: str = "test.structured_log"):
    """造一个独立 logger + StringIO handler(挂 JSONFormatter)。

    yield (logger, stream); 退出时移除 handler, 但**不关闭** stream
    (StreamHandler.close 会关底层流), 让用例在 with 块外仍能读 stream。
    """
    log = logging.getLogger(name)
    log.setLevel(logging.DEBUG)
    log.propagate = False  # 不冒泡到 root, 避免污染全局
    stream = io.StringIO()
    handler = logging.StreamHandler(stream)
    handler.setFormatter(JSONFormatter())
    log.addHandler(handler)
    try:
        yield log, stream
    finally:
        # flush 确保所有日志已写入; 不 close handler(它会关 stream),
        # 用例在 with 块外读 stream 内容
        handler.flush()
        log.removeHandler(handler)


def _reset_trace_ctx() -> None:
    """兜底清空 trace/span contextvars(防跨用例污染)。"""
    for var in (TRACE, SPAN):
        # ContextVar 没有 clear; 用 set default 再 reset token 的等价做法:
        # 直接 set None 会覆盖外层, 测试用例独立运行无外层, set None 即可
        var.set(None)


@pytest.fixture(autouse=True)
def _isolate_trace_ctx():
    """每条用例前后确保 trace_id/span_id 为 None。"""
    _reset_trace_ctx()
    yield
    _reset_trace_ctx()


# --------------------------------------------------------------------- format
class TestJSONFormatter:
    """JSONFormatter 输出契约。"""

    def test_output_is_valid_json(self) -> None:
        # 用例 1: format() 输出是合法单行 JSON
        with _capture_logger() as (log, stream):
            log.info("hello world")
        data = json.loads(stream.getvalue().strip())
        assert isinstance(data, dict)

    def test_required_fields_present(self) -> None:
        # 用例 2: ts / level / logger / msg 齐全且类型合理
        with _capture_logger(name="svc.test") as (log, stream):
            log.warning("boom")
        data = json.loads(stream.getvalue().strip())
        assert data["ts"].endswith("Z")
        assert data["level"] == "WARNING"
        assert data["logger"] == "svc.test"
        assert data["msg"] == "boom"
        # trace_id / span_id / fields 键必须存在(值可为 None / {})
        assert "trace_id" in data
        assert "span_id" in data
        assert "fields" in data

    def test_extra_fields_collected(self) -> None:
        # 用例 5: record 的非标准属性进 fields
        with _capture_logger() as (log, stream):
            log.info("with meta", extra={"user_id": 42, "action": "login"})
        data = json.loads(stream.getvalue().strip())
        assert data["fields"]["user_id"] == 42
        assert data["fields"]["action"] == "login"


# --------------------------------------------------------------------- context
class TestTraceContext:
    """trace_context 上下文传播。"""

    def test_trace_id_consistent_inside_none_outside(self) -> None:
        # 用例 3: 上下文内所有日志 trace_id 一致, 退出后为 None
        with _capture_logger() as (log, stream):
            log.info("before")  # 上下文外
            with trace_context("trace-abc") as tid:
                assert tid == "trace-abc"
                log.info("inside 1")
                log.info("inside 2")
            log.info("after")  # 退出上下文
        lines = [json.loads(ln) for ln in stream.getvalue().splitlines() if ln.strip()]
        before, in1, in2, after = lines
        assert before["trace_id"] is None
        assert in1["trace_id"] == "trace-abc"
        assert in2["trace_id"] == "trace-abc"
        assert after["trace_id"] is None

    def test_nested_trace_inherits_trace_id_new_span_id(self) -> None:
        # 用例 4: 嵌套子 span 继承 trace_id, span_id 变化
        with trace_context("outer-trace") as outer_tid:
            outer_span = SPAN.get()
            with trace_context():  # 不传 trace_id, 应继承外层
                inner_tid = get_trace_id()
                inner_span = SPAN.get()
            assert inner_tid == outer_tid == "outer-trace"
            assert inner_span != outer_span
            # 退出内层后 span 恢复到外层
            assert SPAN.get() == outer_span

    def test_default_trace_id_autogenerated(self) -> None:
        # 不传 trace_id 时自动生成 uuid4 hex(32 位十六进制)
        with trace_context() as tid:
            assert isinstance(tid, str)
            assert len(tid) == 32
            int(tid, 16)  # 合法十六进制
            assert get_trace_id() == tid


# --------------------------------------------------------------------- get_trace
class TestGetTraceId:
    """get_trace_id 行为。"""

    def test_outside_none_inside_nonempty(self) -> None:
        # 用例 6: 上下文外 None, 上下文内非空且与 yield 一致
        assert get_trace_id() is None
        with trace_context("tid-xyz") as tid:
            assert get_trace_id() == tid == "tid-xyz"
        assert get_trace_id() is None


# --------------------------------------------------------------------- install
class TestInstallJsonLogging:
    """install_json_logging 幂等装配 + root 不被重复挂 JSON handler。"""

    def test_install_idempotent_no_duplicate_json_handler(self) -> None:
        root = logging.getLogger()
        # 自包含: 先清掉其他测试(如 web_api lifespan 触发 app.py install_json_logging)
        # 残留在 root 上的 JSON handler, 避免计数污染(before 必须 == 0)。
        for h in list(root.handlers):
            if isinstance(h.formatter, JSONFormatter):
                root.removeHandler(h)
        before = [h for h in root.handlers if isinstance(h.formatter, JSONFormatter)]
        assert before == [], "清理后 root 不应残留 JSON handler"
        h1 = install_json_logging()
        h2 = install_json_logging()  # 二次调用不应再添加
        after = [h for h in root.handlers if isinstance(h.formatter, JSONFormatter)]
        assert len(after) - len(before) == 1
        # 幂等: 二次调用返回同一 handler(已存在则复用), 不重复添加
        assert h2 is h1
        # 清理: 移除本次测试新增的 handler
        root.removeHandler(h1)
